cluster.name: "docker-cluster"
network.host: 0.0.0.0
http.cors.enabled: true  #是否支持跨域，默认为false
http.cors.allow-origin: "*"  #当设置允许跨域，默认为*,表示支持所有域名，如果我们只是允许某些网站能访问，那么可以使用正则表达式。比如只允许本地地址。 /https?:\/\/localhost(:[0-9]+)?/